name: Deploy complexfib

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Build react test docker image"
        run: docker build ./client --file ./client/Dockerfile.dev --tag samueladekunle2002/complexfib_client-test

      - name: Run the jest tests
        run: docker run -e CI=true samueladekunle2002/complexfib_client-test npm run test:ci

  publish:
    needs: [ test ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build images
        run: |
          docker build ./client --file ./client/Dockerfile -t samueladekunle2002/complexfib_client
          docker build ./nginx --file ./nginx/Dockerfile -t samueladekunle2002/complexfib_nginx
          docker build ./server --file ./server/Dockerfile -t samueladekunle2002/complexfib_server
          docker build ./worker --file ./worker/Dockerfile -t samueladekunle2002/complexfib_worker

      - name: Authenticate docker hub
        run: docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish images to docker hub
        run: |
          docker push samueladekunle2002/complexfib_client
          docker push samueladekunle2002/complexfib_nginx
          docker push samueladekunle2002/complexfib_server
          docker push samueladekunle2002/complexfib_worker