name: Deploy complexfib

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Build react test docker image"
        run: docker build ./client --file ./client/Dockerfile.dev --tag samueladekunle2002/complexfib_client-test

      - name: Run the jest tests
        run: docker run -e CI=true samueladekunle2002/complexfib_client-test npm run test:ci

  publish:
    needs: [ test ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build images
        run: |
          docker build ./client --file ./client/Dockerfile -t samueladekunle2002/complexfib_client
          docker build ./nginx --file ./nginx/Dockerfile -t samueladekunle2002/complexfib_nginx
          docker build ./server --file ./server/Dockerfile -t samueladekunle2002/complexfib_server
          docker build ./worker --file ./worker/Dockerfile -t samueladekunle2002/complexfib_worker

      - name: Authenticate docker hub
        run: docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish images to docker hub
        run: |
          docker push samueladekunle2002/complexfib_client
          docker push samueladekunle2002/complexfib_nginx
          docker push samueladekunle2002/complexfib_server
          docker push samueladekunle2002/complexfib_worker

  deploy:
    needs: [ publish ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          role-to-assume: arn:aws:iam::953022703393:user/complexfib-deploy

      - name: Upload docker compose file to S3
        run: aws s3 cp docker-compose.yml s3://elasticbeanstalk-eu-west-2-953022703393/docker-compose-${{ github.sha }}.yml

      - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name complexfib \
            --version-label "complexfib-ver-${{ github.sha }}" \
            --description "commit-sha-${{ github.sha }}" \
            --source-bundle "S3Bucket=elasticbeanstalk-eu-west-2-953022703393,S3Key=docker-compose-${{ github.sha }}.yml"

      - name: Deploy new ElasticBeanstalk Application Version
        run: aws elasticbeanstalk update-environment \
          --environment-name Complexfib-env \
          --version-label "complexfib-ver-${{ github.sha }}"