name: Deploy complexfib

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build images
        run: |
          docker build ./client --file ./client/Dockerfile -t samueladekunle/complexfib_client
          docker build ./nginx --file ./nginx/Dockerfile -t samueladekunle/complexfib_nginx
          docker build ./server --file ./server/Dockerfile -t samueladekunle/complexfib_server
          docker build ./worker --file ./worker/Dockerfile -t samueladekunle/complexfib_worker

      - name: Authenticate docker hub
        run: docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish images to docker hub
        run: |
          docker push samueladekunle/complexfib_client
          docker push samueladekunle/complexfib_nginx
          docker push samueladekunle/complexfib_server
          docker push samueladekunle/complexfib_worker